version: "2.1"

services:
  webapp:
    extends:
      service: webapp
      file: ./docker-services.yml
    command: /bin/sh -c "gunicorn config.wsgi:application --config file:config/gunicorn.py"
    ports:
      - 8010:8000
    networks:
      - main
    depends_on:
      - redis
      - rabbitmq
      - postgres

  worker:
    extends:
        service: webapp
        file: ./docker-services.yml
    command: /bin/sh -c "celery -A config.celery worker --loglevel=INFO --concurrency=4 -Q general-${CELERY_ID}"
    networks:
      - main
    depends_on:
      - redis
      - rabbitmq
      - postgres

  worker_transactions:
    extends:
       service: webapp
       file: ./docker-services.yml
    command: /bin/sh -c "celery -A config.celery worker --loglevel=INFO --concurrency=4 -Q transaction-${CELERY_ID}"
    networks:
      - main
    depends_on:
      - redis
      - rabbitmq
      - postgres

  worker_general:
    extends:
       service: webapp
       file: ./docker-services.yml
    command: /bin/sh -c "celery -A config.celery worker --loglevel=INFO --concurrency=4 -Q general-${CELERY_ID}"
    networks:
      - main
    depends_on:
      - redis
      - rabbitmq
      - postgres

  worker_webhooks:
    extends:
       service: webapp
       file: ./docker-services.yml
    command: /bin/sh -c "celery -A config.celery worker --loglevel=INFO --concurrency=1 -Q webhook-${CELERY_ID}"
    networks:
      - main
    depends_on:
      - redis
      - rabbitmq
      - postgres

  worker_notifications:
    extends:
       service: webapp
       file: ./docker-services.yml
    command: /bin/sh -c "celery -A config.celery worker --loglevel=INFO --concurrency=4 -Q notification-${CELERY_ID}"
    networks:
      - main
    depends_on:
      - redis
      - rabbitmq
      - postgres

  scheduler:
    extends:
       service: webapp
       file: ./docker-services.yml
    command: /bin/sh -c "celery -A config.celery worker --beat --loglevel=INFO --pidfile= --concurrency=1 -Q dummy-queue-${CELERY_ID}"
    networks:
      - main
    depends_on:
      - redis
      - rabbitmq
      - postgres

  postgres:
    image: postgres:9.6
    ports:
      - '${LOCAL_POSTGRES_PORT}:5432'
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      main:
        aliases:
          - postgres

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      main:
        aliases:
          - redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      main:
        aliases:
          - rabbitmq

volumes:
  pgdata:
  newdata:

networks:
  main:
