# Default values for rehive-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
deployment:
  replicaCount: 3
  resources:
    requests:
      memory: 450M
      cpu: 500m
image:
  repository: gcr.io/rehive-core/rehive-core
  tag: latest
  pullPolicy: Always
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 8000
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8000
    initialDelaySeconds: 10
    timeoutSeconds: 2
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /readiness
      port: 8000
    initialDelaySeconds: 10
    timeoutSeconds: 2
    periodSeconds: 10
ingress:
  enabled: true
  hosts:
    - staging3.rehive.com
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"
  tls:
    - hosts:
      - staging3.rehive.com
      secretName: rehive-core-dev
  hosts:
    - staging3.rehive.com
postgres:
  enabled: true
  host: patroni-rehive-core-patroni.rehive-core-staging.svc.cluster.local
  user: admin
  port: 5432
  secret:
    name: patroni-rehive-core-patroni
    key: password-admin
redis:
  enabled: true
  host: redis-rehive-core-redis.rehive-core-staging.svc.cluster.local
  port: 6379
  secret:
    name: redis-rehive-core-redis
    key: redis-password
rabbitmq:
  enabled: true
  host: rabbitmq-ha-rehive-core-rabbitmq-ha.rehive-core-staging.svc.cluster.local
  port: 5672
  secret:
    name: rabbitmq-ha-rehive-core-rabbitmq-ha
    key: rabbitmq-password
workersEnabled: true
workers:
  - name: worker-general
    internalPort: 8000
    replicaCount: 1
    command: 'celery -A config.celery worker --loglevel=INFO --concurrency=1 --without-gossip --without-mingle --without-heartbeat -Q general-rehive-core-staging'
    resources:
      requests:
        memory: 256M
        cpu: 66m
      limits:
        memory: 256M
        cpu: 66m
  - name: worker-notifications
    internalPort: 8000
    replicaCount: 1
    command: 'celery -A config.celery worker --loglevel=INFO --concurrency=1 --without-gossip --without-mingle --without-heartbeat -Q notification-rehive-core-staging'
    resources:
      requests:
        memory: 256M
        cpu: 66m
      limits:
        memory: 256M
        cpu: 66m
  - name: worker-transactions
    internalPort: 8000
    replicaCount: 1
    command: 'celery -A config.celery worker --loglevel=INFO --concurrency=1 --without-gossip --without-mingle --without-heartbeat -Q transaction-rehive-core-staging'
    resources:
      requests:
        memory: 256M
        cpu: 66m
      limits:
        memory: 256M
        cpu: 66m
  - name: worker-webhooks
    internalPort: 8000
    replicaCount: 1
    command: 'celery -A config.celery worker --loglevel=INFO --concurrency=1 --without-gossip --without-mingle --without-heartbeat -Q webhook-rehive-core-staging'
    resources:
      requests:
        memory: 256M
        cpu: 66m
      limits:
        memory: 256M
        cpu: 66m
